# Generated by Django 3.1 on 2020-08-10 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=8)),
            ],
        ),
    ]
